### PR TITLE
Discussion of Additions/Issues

### PR DESCRIPTION
**Pull request by Cattn**
There's no issues tab, so I'm going to make a PR for it, but this is going to be used mainly as a thread of what needs to be fixed up, and also my suggestions

### CODE REVIEW

**Comment by Cattn** [comment]
I'm going to assume the games will be dynamically loaded in from your library eventually, but as of now those pre-set assets seem to be slowing down the page quite a bit (at least when testing with electron) prob because of the loading, if you don't have this issue, where animations/CSS seems like it's stuttering lmk

**Comment by mightyowl866** [comment]
Yes, there does appear to be some significant slowdown when running the program. So far, it occurs for me when entering the main menu, alt-tabbing in and out, and moving the window for the program. Removing these placeholders (afaik) significantly improves performance. 

 Haven't had much of a chance to optimize the program, so sorry about that!

**Comment by mightyowl866** [comment]
Also, I've just created an issues tab for the repo. :)

**Comment by Cattn** [comment]
> Yes, there does appear to be some significant slowdown when running the program. So far, it occurs for me when entering the main menu, alt-tabbing in and out, and moving the window for the program. Removing these placeholders (afaik) significantly improves performance.
> 
> Haven't had much of a chance to optimize the program, so sorry about that!

All good, was just trying to lay it out somewhere to make sure it was a known issue/priority 

Although let me move this all to the Issues tab now

**Pull request closed without merging**
